/**
 * File Manager Module
 * Handles preview rendering and ZIP download of generated project files.
 * Uses the JSZip library (loaded via CDN in index.html).
 */
class FileManager {
    constructor() {
        this.files = {};   // { "path": "content" }
        this._previewUrl = null;
    }

    /**
     * Set the generated files.
     * @param {object} files - Map of { filePath: content }
     */
    setFiles(files) {
        this.files = files || {};
        // Revoke any previous preview blob URL
        if (this._previewUrl) {
            URL.revokeObjectURL(this._previewUrl);
            this._previewUrl = null;
        }
    }

    /**
     * Build a combined HTML string for live preview.
     * Inlines CSS and JS so the iframe can render correctly.
     * @returns {string} Complete HTML document
     */
    createPreviewHTML() {
        const htmlFiles = Object.entries(this.files)
            .filter(([p]) => p.endsWith('.html'));

        const cssFiles = Object.entries(this.files)
            .filter(([p]) => p.endsWith('.css'));

        const jsFiles = Object.entries(this.files)
            .filter(([p]) => p.endsWith('.js'));

        // Use the first HTML file as the base
        let baseHTML = htmlFiles.length > 0 ? htmlFiles[0][1] : this._buildDefaultHTML();

        // Inject CSS
        if (cssFiles.length > 0) {
            const styleTag = `<style>\n${cssFiles.map(([, c]) => c).join('\n\n')}\n</style>`;
            if (baseHTML.includes('</head>')) {
                baseHTML = baseHTML.replace('</head>', `${styleTag}\n</head>`);
            } else {
                baseHTML = styleTag + '\n' + baseHTML;
            }
        }

        // Inject JS
        if (jsFiles.length > 0) {
            const scriptTag = `<script>\n${jsFiles.map(([, c]) => c).join('\n\n')}\n</script>`;
            if (baseHTML.includes('</body>')) {
                baseHTML = baseHTML.replace('</body>', `${scriptTag}\n</body>`);
            } else {
                baseHTML = baseHTML + '\n' + scriptTag;
            }
        }

        return baseHTML;
    }

    /**
     * Build a minimal fallback HTML when no HTML file was generated.
     * @returns {string}
     */
    _buildDefaultHTML() {
        return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generated Project</title>
</head>
<body>
    <h1>Generated Project</h1>
    <p>No HTML file was generated. Check the ZIP download for all files.</p>
</body>
</html>`;
    }

    /**
     * Render the preview in the iframe.
     */
    displayPreview() {
        const iframe = document.getElementById('previewFrame');
        if (!iframe) return;

        const html = this.createPreviewHTML();
        const blob = new Blob([html], { type: 'text/html' });
        this._previewUrl = URL.createObjectURL(blob);
        iframe.src = this._previewUrl;
    }

    /**
     * Create and download a ZIP archive of all generated files.
     * Requires JSZip to be loaded.
     */
    async downloadZip() {
        if (typeof JSZip === 'undefined') {
            throw new Error('JSZip library is not loaded. Check your internet connection.');
        }

        const zip = new JSZip();
        const fileCount = Object.keys(this.files).length;

        if (fileCount === 0) {
            throw new Error('No files to download. Generate a project first.');
        }

        // Add all generated files to the ZIP
        Object.entries(this.files).forEach(([filePath, content]) => {
            zip.file(filePath, content);
        });

        // Add a README
        zip.file('README.md', this._buildReadme());

        // Generate and download
        const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = 'generated-project.zip';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }

    /**
     * Build a simple README for the generated project.
     * @returns {string}
     */
    _buildReadme() {
        const stats = this.getStatistics();
        const fileList = Object.keys(this.files)
            .sort()
            .map(p => `- \`${p}\``)
            .join('\n');

        return `# Generated Project

Generated by AI Frontend Generator.

## Files
${fileList}

## Statistics
- Total files: ${stats.totalFiles}
- HTML files: ${stats.htmlFiles}
- CSS files: ${stats.cssFiles}
- JavaScript files: ${stats.jsFiles}
- Total size: ~${stats.totalSizeKB} KB

## Getting Started

Open \`index.html\` in your browser or serve with a local server:

\`\`\`bash
npx serve .
# or
python -m http.server 8000
\`\`\`

Generated on: ${new Date().toLocaleString()}
`;
    }

    /**
     * Return basic statistics about the generated project.
     * @returns {object}
     */
    getStatistics() {
        const paths = Object.keys(this.files);
        const totalSize = Object.values(this.files)
            .reduce((sum, c) => sum + c.length, 0);

        return {
            totalFiles: paths.length,
            htmlFiles: paths.filter(p => p.endsWith('.html')).length,
            cssFiles:  paths.filter(p => p.endsWith('.css')).length,
            jsFiles:   paths.filter(p => p.endsWith('.js')).length,
            totalSizeKB: Math.round(totalSize / 1024)
        };
    }
}
